// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Request, Response, Router } from 'express';

import { logger } from '../services/logger.service';

/**
 * Public route handler for `/sitemap.xml`. Serves the build-time-generated
 * sitemap (research R9) under `Content-Type: application/xml`. The file is
 * read once at module load and cached in memory — crawlers hammer this URL
 * and we want zero per-request filesystem cost.
 *
 * The sitemap is regenerated by `apps/lfx-one/scripts/build-docs.mjs` on
 * every `prebuild` / `predev`, so a fresh deploy always carries a fresh
 * sitemap. Cache miss (file absent) is treated as 404 rather than 500 — it
 * means the docs build hasn't run yet, which is recoverable by an operator
 * without the page returning a scary error to a crawler.
 */
const SITEMAP_FILE = resolveSitemapPath();
const sitemapBuffer = readSitemapAtStartup(SITEMAP_FILE);

function resolveSitemapPath(): string {
  // server.ts is bundled into dist/lfx-one/server/, two levels above the repo's
  // dist-docs/ directory. Resolve via fileURLToPath so this works whether
  // running under ts-node, ng serve, or the production bundle.
  const here = dirname(fileURLToPath(import.meta.url));
  // dev/ts-node:    apps/lfx-one/src/server/routes  → ../../../dist-docs/sitemap.xml
  // ng-built bundle: dist/lfx-one/server            → ../../../dist-docs/sitemap.xml
  // Both happen to resolve up three levels from the routes/server dir to the
  // workspace's apps/lfx-one root, then into dist-docs/. Try the dev path
  // first; fall back to the build-time path if the file isn't there.
  const devPath = resolve(here, '..', '..', '..', 'dist-docs', 'sitemap.xml');
  const builtPath = resolve(here, '..', '..', 'dist-docs', 'sitemap.xml');
  return devPath || builtPath;
}

function readSitemapAtStartup(path: string): Buffer | null {
  try {
    return readFileSync(path);
  } catch (err) {
    // Don't crash the server: an absent sitemap means `yarn docs:build` hasn't
    // run; the route handler returns 404 and an operator can investigate.
    logger.warning(undefined, 'sitemap_route', 'sitemap.xml not found at startup', {
      path,
      error: err instanceof Error ? err.message : String(err),
    });
    return null;
  }
}

const router = Router();

router.get('/sitemap.xml', (_req: Request, res: Response): void => {
  if (!sitemapBuffer) {
    res.status(404).type('text/plain').send('sitemap.xml not generated');
    return;
  }
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=300');
  res.send(sitemapBuffer);
});

export default router;
