// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { Request, Response, Router } from 'express';

import { logger } from '../services/logger.service';

/**
 * Public route handler for `/sitemap.xml`. Serves the build-time-generated
 * sitemap (research R9) under `Content-Type: application/xml`. The file is
 * read once at module load and cached in memory — crawlers hammer this URL
 * and we want zero per-request filesystem cost.
 *
 * The sitemap is regenerated by `apps/lfx-one/scripts/build-docs.mjs`,
 * which is chained as `yarn docs:build &&` into every `start`, `build*`,
 * `watch`, and `test` script in `apps/lfx-one/package.json`, so a fresh
 * deploy always carries a fresh sitemap. Cache miss (file absent) is treated as 404 rather than 500 — it
 * means the docs build hasn't run yet, which is recoverable by an operator
 * without the page returning a scary error to a crawler.
 *
 * Architectural deviation from the controller-service-route triad
 * (`docs/reviews/backend-checklist.md` §1): this file intentionally
 * collapses the three layers because there is no business logic and no
 * external service to abstract — it reads a static build artifact and
 * emits it verbatim. Splitting into a `SitemapService.getSitemap()`,
 * `SitemapController.serve()`, and a route registration would add three
 * files of indirection over a single `readFileSync` call. If this ever
 * grows real logic (per-request generation, dynamic URLs, env-aware
 * canonical hosts, etc.), it should be split out at that point.
 */
const SITEMAP_FILE = resolveSitemapPath();
const sitemapBuffer = readSitemapAtStartup(SITEMAP_FILE);

function resolveSitemapPath(): string {
  // Both runtime layouts place this file three directory levels below
  // `apps/lfx-one/`, so a single 3-up climb resolves to the workspace
  // root in either case:
  //
  //   dev / ts-node     : apps/lfx-one/src/server/routes/sitemap.route.ts
  //                       → ../../../  → apps/lfx-one
  //   ng-built bundle   : apps/lfx-one/dist/lfx-one/server/server.mjs
  //                       → ../../../  → apps/lfx-one
  //
  // The build pipeline (`scripts/build-docs.mjs`, invoked via the
  // `yarn docs:build` step chained into each start/build script) emits
  // the sitemap to `apps/lfx-one/dist-docs/sitemap.xml`, so the resolved
  // path is correct in dev, in `ng serve`, and in the
  // production server bundle. (An earlier version of this function had
  // a second `../../dist-docs` candidate intended as a "production"
  // fallback, but it actually pointed at `dist/dist-docs/sitemap.xml` —
  // the path was off by one level. existsSync hid the bug because the
  // working candidate fired first; the broken candidate is removed
  // here and `readSitemapAtStartup` logs a clear warning if the file
  // is missing for any reason.)
  const here = dirname(fileURLToPath(import.meta.url));
  return resolve(here, '..', '..', '..', 'dist-docs', 'sitemap.xml');
}

function readSitemapAtStartup(path: string): Buffer | null {
  try {
    return readFileSync(path);
  } catch (err) {
    // Don't crash the server: an absent sitemap means `yarn docs:build` hasn't
    // run; the route handler returns 404 and an operator can investigate.
    // Log via the `err` field so Pino's serializer keeps the stack trace
    // and any custom error properties.
    logger.warning(undefined, 'sitemap_route', 'sitemap.xml not found at startup', {
      path,
      err,
    });
    return null;
  }
}

const router = Router();

router.get('/sitemap.xml', (_req: Request, res: Response): void => {
  if (!sitemapBuffer) {
    res.status(404).type('text/plain').send('sitemap.xml not generated');
    return;
  }
  res.setHeader('Content-Type', 'application/xml; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=300');
  res.send(sitemapBuffer);
});

export default router;
