# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Quality Checks

# DISABLED: Moving away from old UI - quality checks no longer needed
# Changed to manual trigger only - will not run automatically on PRs
on:
  workflow_dispatch:

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check formatting
        run: yarn format:check

      - name: Run linting
        run: yarn lint:check

      - name: Type checking
        run: yarn check-types

      - name: Build project
        run: yarn build

  e2e-tests:
    name: E2E Tests
    needs: quality-checks
    uses: ./.github/workflows/e2e-tests.yml
    with:
      node-version: "22"
      test-command: "e2e"
      browser: "chromium" # Use only Chromium for PR testing for faster feedback
      skip-build: false
    secrets:
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      AI_API_KEY: ${{ secrets.AI_API_KEY }}
      AI_PROXY_URL: ${{ secrets.AI_PROXY_URL }}
